# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4c0f7a935ca6af8bf31ee5c44e96835dd51013f857be166ca21c8eca36914925982a1a7ed6d1872b8bc25c50d93e4ffd446e9e9aac51b862c8d2c332b73da64

test:
  secret_key_base: a3cf2857941a927cc65fd558b67e68b9e9cd690beb3d289197c0e711b81dc5b8a895d0c22279a2ab1b6dbcc6e2859f3d1feb889550809e4878450b2342f529a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
